import Head from "next/head";
import Card from "@/components/main-page/card";
import {
  StyledContainer,
  StyledLanguageButton,
} from "@/components/ready-to-use/styles";
import { useLanguage } from "@/context/language-context";

export default function Home() {
  const { selectedLanguage, handleSetSelectedLanguage } = useLanguage();
  return (
    <>
      <Head>
        <title>Github repositories explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledContainer>
        <StyledLanguageButton
          onClick={handleSetSelectedLanguage}
          variant="contained"
        >
          {selectedLanguage}
        </StyledLanguageButton>
        <Card />
      </StyledContainer>
    </>
  );
}
